#!/bin/bash

# -*-  Coding: UTF-8  -*- #
# -*-  System: Linux  -*- #
# -*-  Usage:  *.Yaml -*- #

# Owner: Jacob B. Sanders
# Source: code.cloud-technology.io
# License: BSD 3-Clause License

#
# Copyright 2020 Jacob B. Sanders - Cloud Hybrid LLC. & Affiliates
#
# Redistribution and use in source and binary forms, with or without modification, are permitted
# provided that the following conditions are met:
#
# 1.  Redistributions of source code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#
# 2.  Redistributions in binary form must reproduce the above copyright notice, this list of
#     conditions and the following disclaimer in the documentation and/or other materials
#     provided with the distribution.
#
# 3.  Neither the name of the copyright holder nor the names of its contributors may be used
#     to endorse or promote products derived from this software without specific prior written
#     permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE
#

#
# ========================================================================
# Global Environment Parser
# ========================================================================
#
# @TODO: Enforce Parameter ${1} is `Environment.env` Full-System Path
#        - `Environment.env` should come from Git Root Directory
#
# Command-Line Usage (POSIX Bash, Shell)
# ------------------------------------------------------------------------
# >>> ./Environment Project-Name Version ISO 8601
#
# Example *.ini Reading --> *.env File
# ------------------------------------------------------------------------
# >>> tr -d '\r' < "${CWD}/Environment.ini" > "${CWD}/Environment.unix"
# >>> while IFS=" = " read -r NAME VALUE
# >>>    do
# >>>        if [[ ! $NAME =~ ^\ *# && -n $VALUE ]]; then
# >>>            COMMENTS="${VALUE%%\#*}"
# >>>            SPACES="${COMMENTS%%*( )}"
# >>>            LHS="${SPACES%\"*}"
# >>>            RHS="${LHS#\"*}"
# >>>
# >>>            printf "%s\n" "${NAME}=${VALUE}"    \
# >>>                >> "${CWD}/Environment.env"     \
# >>>                && echo -e "\n\t ${NAME} ➜ ${VALUE}\n"
# >>>        fi
# >>>    done < "${CWD}/Environment.unix"
#

CWD="$( cd "$(dirname "${0}" )" > /dev/null 2>&1 ; pwd -P )"

( rm -r -f "${CWD}/Environment.env" ) 1>/dev/null 2>/dev/null

printf "%s\n" "PROJECT_PATH=${CWD}" >> "${CWD}/Environment.env" \
    && echo -e "\n\t PROJECT_PATH ➜ \"${CWD}\"\n"

printf "%s\n" "PROJECT_NAME=${1}" >> "${CWD}/Environment.env" \
    && echo -e "\n\t PROJECT_NAME ➜ \"${1}\"\n"

printf "%s\n" "PROJECT_VERSION=${2}" >> "${CWD}/Environment.env" \
    && echo -e "\n\t PROJECT_VERSION ➜ \"${2}\"\n"

printf "%s\n" "PROJECT_SHA=${3}" >> "${CWD}/Environment.env" \
    && echo -e "\n\t PROJECT_SHA ➜ \"${3}\"\n"

printf "PROJECT_TIMESTAMP=%s" "$( \
    awk 'BEGIN {srand(); print srand()}' )" \
        >> "${CWD}/Environment.env" && \
            echo -e "\n\t PROJECT_TIMESTAMP ➜ \"$( \
                awk 'BEGIN {srand(); print srand()}' )\"\n"

echo "Complete" && exit 0