#!/usr/bin/env bash

# -*- Coding: UTF-8 -*- #
# -*- System: Linux -*- #
# -*- Usage:   *.*  -*- #

if [ ! -n "${1}" ]; then
	echo "A Key-Name is Required as Input" && exit -1
else
	if [ ! -n "${2}"]; then
		SIGNATURE=$(uuidgen)
	else
		SIGNATURE="${2}"
	fi

	ssh-keygen -b 521 -t ECDSA -f "${1}" -C "${SIGNATURE}" -N ""
fi

echo "Upload Public Key to Server: ([Y]es/[N]o)"
printf "%s" "--> "
read UPL
UPLOAD=""

case $UPL in
  	Yes | Y | y | yes)
		UPLOAD=1
		;;
	No | N | n | no)
		UPLOAD=0
		;;
	*)
		echo "Invalid Input"
		exit -1
		;;
esac

if [[ "${UPLOAD}" == "1" ]]; then
	echo ""
	echo -n "Hostname or IP: "
	read TARGET
	echo -n "User: "
	read SSHUSER
	
	ssh-copy-id -i $1 $(printf "%s@%s" "${SSHUSER}" "${TARGET}")

else
	echo "Good Byte" && exit 0
fi

exit 0
