#!/usr/bin/env python3.8

# -*- Coding: UTF-8 -*- #
# -*- System: Linux -*- #
# -*- Usage:  *.py  -*- #

import os
import time
import shutil

PATH = os.path.abspath(os.path.dirname(__file__))

print(" --- Recursive Clean --- ")

for directory, folders, files in os.walk(PATH):
    if (Target := directory.split("/")[-1]) == "__pycache__":
        print()
        print(" *** Removing: {}".format(directory))
        print()
        if input("  |  Continue? (Y/N): ").casefold() == "y":
            shutil.rmtree(directory)
    print("{} - {}".format(" " * 0, directory))
    for folder in folders:
        print("{} - {}".format(" " * 3, folder))
    for file in files:
        print("{} - {}".format(" " * 3, file))

